apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      app: nginx-web
  
  template:
    metadata:
      labels:
        app: nginx-web
    
    spec:
      containers:
      - name: nginx-web
  
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-svc
spec:
  selector:
    app: nginx-web
  ports:
  - port: 80
    targetPort: 80
