apiVersion: v1
kind: Namespace
metadata:
  name: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-web
  namespace: httpd
spec:
  selector:
    matchLabels:
      app: httpd-web
  
  template:
    metadata:
      labels:
        app: httpd-web
    
    spec:
      containers:
      - name: httpd-web
  
        image: httpd:2.4.54
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-web-svc
  namespace: httpd
spec:
  selector:
    app: httpd-web
  ports:
  - port: 80
    targetPort: 80
